# Azure OpenAI配置
AZURE_OPENAI_ENDPOINT = "YOUR_AZURE_OPENAI_ENDPOINT"
AZURE_OPENAI_DEPLOYMENT_NAME =  "YOUR_DEPLOYMENT_NAME"
# AZURE_OPENAI_DEPLOYMENT_NAME =  "YOUR_DEPLOYMENT_NAME"
AZURE_OPENAI_API_VERSION = "2025-03-01-preview"
AZURE_OPENAI_SCOPE = "YOUR_AZURE_OPENAI_SCOPE"

# 处理配置
MAX_FILES_TO_PROCESS = 10  # 处理文件数量限制
API_DELAY_SECONDS = 1  # API调用间隔
MAX_TOKENS = 4096  # 最大token数
TEMPERATURE = 0.7  # 温度参数

# 路径配置
INPUT_DIRECTORY = "valid_scenes_extracted"
OUTPUT_DIRECTORY = "conversation_data"
